//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIProject.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class AIProjectDBEntities : DbContext
    {
        public AIProjectDBEntities()
            : base("name=AIProjectDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<RequirementQuestion> RequirementQuestion { get; set; }
        public virtual DbSet<SystemUser> SystemUser { get; set; }
        public virtual DbSet<AIMatrix> AIMatrix { get; set; }
    
        public virtual ObjectResult<SystemUser> SystemUserCheckLogin(string a_Username, string a_Password)
        {
            var a_UsernameParameter = a_Username != null ?
                new ObjectParameter("a_Username", a_Username) :
                new ObjectParameter("a_Username", typeof(string));
    
            var a_PasswordParameter = a_Password != null ?
                new ObjectParameter("a_Password", a_Password) :
                new ObjectParameter("a_Password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SystemUser>("SystemUserCheckLogin", a_UsernameParameter, a_PasswordParameter);
        }
    
        public virtual ObjectResult<SystemUser> SystemUserCheckLogin(string a_Username, string a_Password, MergeOption mergeOption)
        {
            var a_UsernameParameter = a_Username != null ?
                new ObjectParameter("a_Username", a_Username) :
                new ObjectParameter("a_Username", typeof(string));
    
            var a_PasswordParameter = a_Password != null ?
                new ObjectParameter("a_Password", a_Password) :
                new ObjectParameter("a_Password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SystemUser>("SystemUserCheckLogin", mergeOption, a_UsernameParameter, a_PasswordParameter);
        }
    }
}
